### ISSUE TITLE
Reordenar ejercicios de Mover y Poner

### ISSUE THREAD

**Issue by flbulgarelli** [sagrado-corazon-alcal/mumuki-guia-fundamentos-primeros-programas#2]
En la facultad del Quilmes, se suele enseñar primero a poner bolitas y luego a mover el cabezal. Esta guía debería respetar esa idea

**Comment by flbulgarelli** [comment]
@faloi esto todavía tiene sentido? Lo hacemos o lo dejamos así?

**Comment by faloi** [comment]
Implica repensar varios ejercicios, por ahora quedará así.
