### ISSUE TITLE
El corolario de fin de la primer lección tapa al del último ejercicio

### ISSUE THREAD

**Issue by mgarciaisaia** [sagrado-corazon-alcal/mumuki-guia-fundamentos-primeros-programas#4]
Cuando completás correctamente el último ejercicio de la primer lección, el corolario de la lección aparece tapando al del ejercicio:

<img width="1296" alt="screen shot 2016-03-20 at 11 59 28 pm" src="https://cloud.githubusercontent.com/assets/1190974/13910025/9bd0a7f2-eefa-11e5-841d-32541021784e.png">

Dice @flbulgarelli que el último ejercicio de cada lección no debería tener corolario para evitar esto.

**Comment by faloi** [comment]
Como me interesaba el corolario de ese último ejercicio, terminé agregando uno extra con `Sacar`, que igual mal no venía.
