### ISSUE TITLE
"Linea" es ambiguo en cuanto a dirección

### ISSUE THREAD

**Issue by mgarciaisaia** [sagrado-corazon-alcal/mumuki-guia-fundamentos-primeros-programas#5]
En [3.7](http://mumuki.io/exercises/320-fundamentos-procedimientos-dibujarlineanegra3), se presume "linea" como horizontal. Deberían hablar de fila, para matar ambigüedades.

**Comment by faloi** [comment]
Mmmm, coincido con vos en que **para nosotros** es menos ambiguo eso, pero dudo que lo sea para la piba/pibe promedio que va a resolver esa guía. Lo voy a dejar así.
