### ISSUE TITLE
[Intro] Objetivizar la máquina

### ISSUE THREAD

**Issue by faloi** [sagrado-corazon-alcal/mumuki-guia-fundamentos-primeros-programas#6]
La máquina NO entiende.

Revisar:

> El resultado de programar es justamente... ¡un programa! O sea, una descripción de la solución al problema, que de alguna forma puede ser utilizado en una máquina de forma automática para resolver el problema. Al utilizar la máquina y el programa de esta manera decimos que la máquina **ejecuta** el programa.
> 
> Escribir el programa: escribir la solución en un idioma que tanto el humano como la máquina pueden entender - **el lenguaje de programación**.

**Comment by flbulgarelli** [comment]
¿Por qué decís que la máquina no entiende? ¿El problema es el sujeto (la máquina no es quien entiende sino otro elemento?) o el hecho de entender (no te gusta decir que la máquina tenga capacidad de entedimiento?)?

**Comment by flbulgarelli** [comment]
Definitivamente, si no es la máquina, al menos es el motor de Gobstones (otro programa) el que es capaz de tomar las instrucciones y ejecutarlas. Para ello, las instrucciones que recibe deben ser conocidas por éste.

Definitivamente la máquina o el intérprete no tienen capacidad de introspección, pero ¿es necesaria tal capacidad para hablar de entendimiento? Yo entiendo que no :stuck_out_tongue:
